language: bash
addons:
  apt:
    packages:
services:
  - docker
script:
  - make
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make push;
    fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/67a6ba826c798adc9847
    on_success: always
    on_failure: always
    on_start: never
